server:
  port: 8080
spring:
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/test              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 1                                           # 数据库连接池的最小维持连接数
      initial-size: 2                                       # 初始化连接数
      max-total: 20                                          # 最大连接数
      max-wait-millis: 60000                                  # 等待连接获取的最大超时时间
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true                      #开启下划线转驼峰
    cache-enabled: true                                     #开启二级缓存
    lazy-loading-enabled: true                              #开启延迟加载
    